import { CaregiverProfile, Conversation, FacilityProfile, Message, VolunteerProfile, VolunteerTimeSlot } from './store';

// Volunteer signup interface
export interface VolunteerSignup {
  id: string;
  visitorId: string;
  visitorName: string;
  visitorEmail: string;
  visitorPhone: string;
  facilityId: string;
  facilityName: string;
  facilityImage: string;
  facilityAddress: string;
  timeSlotId: string;
  dayOfWeek: string;
  startTime: string;
  endTime: string;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  signupDate: string;
  hoursLogged?: number;
}

// Available volunteer skills
export const volunteerSkills = [
  'Companionship',
  'Games',
  'Music',
  'Reading',
  'Arts & Crafts',
  'Gardening',
  'Pet Therapy',
  'Exercise',
  'Technology Help',
  'Cooking',
];

export const mockFacilities: FacilityProfile[] = [
  {
    id: 'f1',
    name: 'Sunrise Senior Care',
    email: 'contact@sunrisesenior.com',
    phone: '(555) 123-4567',
    userType: 'facility',
    facilityName: 'Sunrise Senior Care Home',
    address: '1234 Oak Street, Los Angeles, CA 90001',
    location: 'Los Angeles, CA',
    bio: 'A warm, family-oriented board and care home providing personalized attention in a comfortable setting.',
    capacity: 12,
    currentResidents: 8,
    amenities: ['Private Rooms', 'Garden', 'TV Lounge', 'Wheelchair Accessible', 'Pet Friendly'],
    services: ['24/7 Care', 'Medication Management', 'Meals Provided', 'Transportation', 'Physical Therapy'],
    priceRange: '$3,500 - $5,000/month',
    rating: 4.8,
    reviewCount: 47,
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    licensed: true,
    avatar: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=200',
    volunteerHours: [
      { id: 'vh1', dayOfWeek: 'Monday', startTime: '9:00 AM', endTime: '12:00 PM', spotsAvailable: 3 },
      { id: 'vh2', dayOfWeek: 'Wednesday', startTime: '2:00 PM', endTime: '5:00 PM', spotsAvailable: 2 },
      { id: 'vh3', dayOfWeek: 'Saturday', startTime: '10:00 AM', endTime: '2:00 PM', spotsAvailable: 4 },
    ],
  },
  {
    id: 'f2',
    name: 'Golden Years Residence',
    email: 'info@goldenyears.com',
    phone: '(555) 234-5678',
    userType: 'facility',
    facilityName: 'Golden Years Board & Care',
    address: '5678 Palm Avenue, Pasadena, CA 91101',
    location: 'Pasadena, CA',
    bio: 'Luxury assisted living with a focus on dignity, independence, and quality of life.',
    capacity: 8,
    currentResidents: 6,
    amenities: ['Private Suites', 'Spa', 'Library', 'Chef-Prepared Meals', 'Fitness Room'],
    services: ['Memory Care', 'Skilled Nursing', 'Rehabilitation', 'Social Activities', 'Hospice Support'],
    priceRange: '$5,500 - $7,500/month',
    rating: 4.9,
    reviewCount: 62,
    images: [
      'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    licensed: true,
    avatar: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=200',
    volunteerHours: [
      { id: 'vh4', dayOfWeek: 'Tuesday', startTime: '10:00 AM', endTime: '1:00 PM', spotsAvailable: 2 },
      { id: 'vh5', dayOfWeek: 'Thursday', startTime: '3:00 PM', endTime: '6:00 PM', spotsAvailable: 3 },
      { id: 'vh6', dayOfWeek: 'Sunday', startTime: '1:00 PM', endTime: '4:00 PM', spotsAvailable: 2 },
    ],
  },
  {
    id: 'f3',
    name: 'Peaceful Haven',
    email: 'hello@peacefulhaven.com',
    phone: '(555) 345-6789',
    userType: 'facility',
    facilityName: 'Peaceful Haven Senior Home',
    address: '910 Willow Lane, Glendale, CA 91201',
    location: 'Glendale, CA',
    bio: 'Small, intimate care home where every resident is treated like family.',
    capacity: 6,
    currentResidents: 5,
    amenities: ['Shared Rooms', 'Backyard', 'Home-Cooked Meals', 'Family Visits Welcome'],
    services: ['Personal Care', 'Companionship', 'Light Housekeeping', 'Medication Reminders'],
    priceRange: '$2,800 - $3,800/month',
    rating: 4.7,
    reviewCount: 31,
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    licensed: true,
    avatar: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=200',
    volunteerHours: [
      { id: 'vh7', dayOfWeek: 'Monday', startTime: '2:00 PM', endTime: '5:00 PM', spotsAvailable: 2 },
      { id: 'vh8', dayOfWeek: 'Friday', startTime: '10:00 AM', endTime: '1:00 PM', spotsAvailable: 3 },
    ],
  },
  {
    id: 'f4',
    name: 'Comfort Care Living',
    email: 'info@comfortcare.com',
    phone: '(555) 456-7890',
    userType: 'facility',
    facilityName: 'Comfort Care Board & Care',
    address: '2468 Maple Drive, Burbank, CA 91502',
    location: 'Burbank, CA',
    bio: 'Modern facility with experienced staff dedicated to providing exceptional senior care.',
    capacity: 10,
    currentResidents: 7,
    amenities: ['Semi-Private Rooms', 'Activity Room', 'Outdoor Patio', 'WiFi'],
    services: ['Dementia Care', 'Diabetic Care', 'Fall Prevention', 'Social Programs'],
    priceRange: '$4,000 - $5,500/month',
    rating: 4.6,
    reviewCount: 28,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    licensed: true,
    avatar: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=200',
    volunteerHours: [
      { id: 'vh9', dayOfWeek: 'Wednesday', startTime: '9:00 AM', endTime: '12:00 PM', spotsAvailable: 2 },
      { id: 'vh10', dayOfWeek: 'Saturday', startTime: '2:00 PM', endTime: '5:00 PM', spotsAvailable: 4 },
    ],
  },
];

export const mockCaregivers: CaregiverProfile[] = [
  {
    id: 'c1',
    name: 'Maria Santos',
    email: 'maria.s@email.com',
    phone: '(555) 111-2222',
    userType: 'caregiver',
    location: 'Los Angeles, CA',
    bio: 'Compassionate caregiver with 10+ years of experience caring for seniors. Specializing in dementia and Alzheimer\'s care.',
    avatar: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200',
    experience: 10,
    certifications: ['CNA', 'CPR/First Aid', 'Dementia Care Certified'],
    specializations: ['Dementia Care', 'Mobility Assistance', 'Medication Management'],
    hourlyRate: 28,
    availability: 'full_time',
    rating: 4.9,
    reviewCount: 89,
    verified: true,
  },
  {
    id: 'c2',
    name: 'James Wilson',
    email: 'james.w@email.com',
    phone: '(555) 222-3333',
    userType: 'caregiver',
    location: 'Pasadena, CA',
    bio: 'Former nurse turned private caregiver. I believe in treating every client with dignity and respect.',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200',
    experience: 15,
    certifications: ['RN', 'CPR/First Aid', 'Hospice Care'],
    specializations: ['Post-Surgery Care', 'Wound Care', 'Physical Therapy Support'],
    hourlyRate: 35,
    availability: 'part_time',
    rating: 4.8,
    reviewCount: 124,
    verified: true,
  },
  {
    id: 'c3',
    name: 'Elena Rodriguez',
    email: 'elena.r@email.com',
    phone: '(555) 333-4444',
    userType: 'caregiver',
    location: 'Glendale, CA',
    bio: 'Bilingual caregiver (English/Spanish) with a gentle approach and excellent cooking skills.',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200',
    experience: 7,
    certifications: ['HHA', 'CPR/First Aid'],
    specializations: ['Companionship', 'Meal Preparation', 'Light Housekeeping'],
    hourlyRate: 24,
    availability: 'live_in',
    rating: 4.7,
    reviewCount: 56,
    verified: true,
  },
  {
    id: 'c4',
    name: 'David Chen',
    email: 'david.c@email.com',
    phone: '(555) 444-5555',
    userType: 'caregiver',
    location: 'Burbank, CA',
    bio: 'Experienced in caring for seniors with various health conditions. Patient, reliable, and dedicated.',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200',
    experience: 5,
    certifications: ['CNA', 'CPR/First Aid', 'Diabetic Care'],
    specializations: ['Diabetic Care', 'Mobility Assistance', 'Transportation'],
    hourlyRate: 26,
    availability: 'flexible',
    rating: 4.6,
    reviewCount: 42,
    verified: true,
  },
  {
    id: 'c5',
    name: 'Sarah Thompson',
    email: 'sarah.t@email.com',
    phone: '(555) 555-6666',
    userType: 'caregiver',
    location: 'Los Angeles, CA',
    bio: 'Caring for seniors is my passion. I specialize in memory care and creating engaging activities.',
    avatar: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=200',
    experience: 8,
    certifications: ['CNA', 'CPR/First Aid', 'Memory Care Specialist'],
    specializations: ['Memory Care', 'Activity Planning', 'Emotional Support'],
    hourlyRate: 30,
    availability: 'full_time',
    rating: 4.9,
    reviewCount: 78,
    verified: true,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    participantIds: ['user', 'f1'],
    participantNames: ['You', 'Sunrise Senior Care'],
    participantAvatars: ['', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=200'],
    lastMessage: 'We have availability for a tour this Saturday at 2pm.',
    lastMessageTime: Date.now() - 1000 * 60 * 30,
    unreadCount: 1,
  },
  {
    id: 'conv2',
    participantIds: ['user', 'c1'],
    participantNames: ['You', 'Maria Santos'],
    participantAvatars: ['', 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200'],
    lastMessage: 'I would be happy to discuss your care needs.',
    lastMessageTime: Date.now() - 1000 * 60 * 60 * 2,
    unreadCount: 0,
  },
  {
    id: 'conv3',
    participantIds: ['user', 'f2'],
    participantNames: ['You', 'Golden Years Residence'],
    participantAvatars: ['', 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=200'],
    lastMessage: 'Thank you for your interest in our facility!',
    lastMessageTime: Date.now() - 1000 * 60 * 60 * 24,
    unreadCount: 0,
  },
];

export const mockMessages: Record<string, Message[]> = {
  conv1: [
    {
      id: 'm1',
      senderId: 'f1',
      receiverId: 'user',
      content: 'Hello! Thank you for reaching out to Sunrise Senior Care. How can we help you?',
      timestamp: Date.now() - 1000 * 60 * 60 * 24,
      read: true,
    },
    {
      id: 'm2',
      senderId: 'user',
      receiverId: 'f1',
      content: 'Hi, I\'m looking for a board and care home for my mother. Do you have any availability?',
      timestamp: Date.now() - 1000 * 60 * 60 * 23,
      read: true,
    },
    {
      id: 'm3',
      senderId: 'f1',
      receiverId: 'user',
      content: 'Yes, we currently have 4 spots available. Would you like to schedule a tour?',
      timestamp: Date.now() - 1000 * 60 * 60 * 2,
      read: true,
    },
    {
      id: 'm4',
      senderId: 'user',
      receiverId: 'f1',
      content: 'That would be great! When are you available?',
      timestamp: Date.now() - 1000 * 60 * 60,
      read: true,
    },
    {
      id: 'm5',
      senderId: 'f1',
      receiverId: 'user',
      content: 'We have availability for a tour this Saturday at 2pm.',
      timestamp: Date.now() - 1000 * 60 * 30,
      read: false,
    },
  ],
  conv2: [
    {
      id: 'm6',
      senderId: 'user',
      receiverId: 'c1',
      content: 'Hi Maria, I saw your profile and I\'m interested in hiring a caregiver for my father.',
      timestamp: Date.now() - 1000 * 60 * 60 * 5,
      read: true,
    },
    {
      id: 'm7',
      senderId: 'c1',
      receiverId: 'user',
      content: 'I would be happy to discuss your care needs.',
      timestamp: Date.now() - 1000 * 60 * 60 * 2,
      read: true,
    },
  ],
  conv3: [
    {
      id: 'm8',
      senderId: 'user',
      receiverId: 'f2',
      content: 'Hello, I\'d like more information about your facility.',
      timestamp: Date.now() - 1000 * 60 * 60 * 25,
      read: true,
    },
    {
      id: 'm9',
      senderId: 'f2',
      receiverId: 'user',
      content: 'Thank you for your interest in our facility!',
      timestamp: Date.now() - 1000 * 60 * 60 * 24,
      read: true,
    },
  ],
};

// Mock volunteer signups (for demo user)
export const mockSignups: VolunteerSignup[] = [
  {
    id: 'signup1',
    visitorId: 'v1',
    visitorName: 'John Student',
    visitorEmail: 'john@email.com',
    visitorPhone: '(555) 111-2222',
    facilityId: 'f1',
    facilityName: 'Sunrise Senior Care Home',
    facilityImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400',
    facilityAddress: '1234 Oak Street, Los Angeles, CA 90001',
    timeSlotId: 'vh1',
    dayOfWeek: 'Monday',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    status: 'confirmed',
    signupDate: '2026-02-15',
    hoursLogged: 3,
  },
  {
    id: 'signup2',
    visitorId: 'v1',
    visitorName: 'John Student',
    visitorEmail: 'john@email.com',
    visitorPhone: '(555) 111-2222',
    facilityId: 'f2',
    facilityName: 'Golden Years Board & Care',
    facilityImage: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=400',
    facilityAddress: '5678 Palm Avenue, Pasadena, CA 91101',
    timeSlotId: 'vh4',
    dayOfWeek: 'Tuesday',
    startTime: '10:00 AM',
    endTime: '1:00 PM',
    status: 'pending',
    signupDate: '2026-02-16',
  },
  {
    id: 'signup3',
    visitorId: 'v1',
    visitorName: 'John Student',
    visitorEmail: 'john@email.com',
    visitorPhone: '(555) 111-2222',
    facilityId: 'f3',
    facilityName: 'Peaceful Haven Senior Home',
    facilityImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=400',
    facilityAddress: '910 Willow Lane, Glendale, CA 91201',
    timeSlotId: 'vh7',
    dayOfWeek: 'Monday',
    startTime: '2:00 PM',
    endTime: '5:00 PM',
    status: 'completed',
    signupDate: '2026-02-10',
    hoursLogged: 3,
  },
];
